Make integration tests work under podman
podman was failing with this error due to (apparently) lacking support
for abbreviated sha256 references:

    docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/containers/create: Internal Server Error ("normalizing image: normalizing name for compat API: sha256:a455ef9d0843: invalid format: no 64-byte hexadecimal value")

Using the full SHA256 hash works under podman (and presumably works
under Docker too?).